package com.xworkz.boot;

import com.xworkz.app.Amazon;
import com.xworkz.app.Cred;
import com.xworkz.app.Facebook;
import com.xworkz.app.GitHub;
import com.xworkz.app.Instagram;
import com.xworkz.app.Irctc;
import com.xworkz.app.LinkedIn;
import com.xworkz.app.NammaMetro;
import com.xworkz.app.NammaYatri;
import com.xworkz.app.Netflix;
import com.xworkz.app.Ola;
import com.xworkz.app.PhonePay;
import com.xworkz.app.Pubg;
import com.xworkz.app.Rapido;
import com.xworkz.app.RedBus;
import com.xworkz.app.Snapchat;
import com.xworkz.app.Uber;
import com.xworkz.app.Whatsapp;
import com.xworkz.app.YouTube;

public class MainRunner {
	public static void main(String[] args) {
		System.out.println("Invoking main in EncapsulationRunner");
		System.out.println("Invoking WhatsApp in main");
		whatsapp whatsapp = new Whatsapp();
		whatsapp.setBlockContacts(20);
		whatsapp.setCall("voice call");
		whatsapp.setFingerPrint(true);
		whatsapp.setFontSize(10);
		whatsapp.setFontStyle("Itallic");
		whatsapp.setLanguage("English");
		whatsapp.setLinkedDevices(2);
		whatsapp.setMessageType("Text");
		whatsapp.setNoOfContacts(150);
		whatsapp.setNoOfGroups(15);
		whatsapp.setNumber(8088019824);
		whatsapp.setStorage(25);
		whatsapp.setTheme("Nature");
		whatsapp.setWallPaper("Flower");
		System.out.println(whatsapp.getCall());
		System.out.println(whatsapp.getFontSize());
		System.out.println(whatsapp.getFontStyle());
		System.out.println(whatsapp.getLanguage());
		System.out.println(whatsapp.getMessageType());
		System.out.println(whatsapp.getNoOfGroups());
		System.out.println(whatsapp.getNumber());
		System.out.println(whatsapp.getTheme());
		System.out.println(whatsapp.getWallPaper());
		System.out.println(whatsapp.isBlockContacts());
		System.out.println(whatsapp.isFingerPrint());
		System.out.println(whatsapp.isLinkedDevices());
		System.out.println(whatsapp.isNoOfContacts());
		System.out.println(whatsapp.isStorage());
		System.out.println("++++++++++++++++++++++++++++++++++++++++++");
		System.out.println("Invoking Instagram in main");
		Instagram instagram = new Instagram();
		instagram.setFollowers(400);
		instagram.setId("Harshith");
		instagram.setFollowing(350);
		instagram.setNoOfPosts(15);
		instagram.setFingerPrint(true);
		instagram.setNoOfCloseFriends(30);
		instagram.setTheme("Dark");
		instagram.setLanguage("English");
		instagram.setMessage("Text Message");
		instagram.setStorage(10);
		instagram.setNoOfGroup(10);
		instagram.setFontSize(6);
		instagram.setFontStyle("Itallic");
		instagram.setNoOflikes(100);
		System.out.println(instagram.getFollowers());
		System.out.println(instagram.getId());
		System.out.println(instagram.getFollowing());
		System.out.println(instagram.getNoOfPosts());
		System.out.println(instagram.isFingerPrint());
		System.out.println(instagram.getNoOfCloseFriends());
		System.out.println(instagram.getTheme());
		System.out.println(instagram.getLanguage());
		System.out.println(instagram.getMessage());
		System.out.println(instagram.getStorage());
		System.out.println(instagram.getNoOfGroup());
		System.out.println(instagram.getFontStyle());
		System.out.println(instagram.getFontSize());
		System.out.println(instagram.getNoOflikes());
		System.out.println("++++++++++++++++++++++++++++++++++++++++++");
		System.out.println("Invoking Snapchat in main");
		Snapchat snapchat = new Snapchat();
		snapchat.setTheme("Normal");
		snapchat.setCloseFriends(25);
		snapchat.setNoOfSnaps(15);
		snapchat.setGroups(5);
		snapchat.setChat("Message");
		snapchat.setFriends(35);
		snapchat.setStoryViews(35);
		snapchat.setNoOfFilters(25);
		snapchat.setFont("Italic");
		snapchat.setMusic(true);
		snapchat.setLocation(true);
		snapchat.setFilters(10);
		snapchat.setPrivacy("Public");
		snapchat.setSnapId("harshitha");
		System.out.println(snapchat.getTheme());
		System.out.println(snapchat.getCloseFriends());
		System.out.println(snapchat.getNoOfSnaps());
		System.out.println(snapchat.getGroups());
		System.out.println(snapchat.getChat());
		System.out.println(snapchat.getFriends());
		System.out.println(snapchat.getStoryViews());
		System.out.println(snapchat.getNoOfFilters());
		System.out.println(snapchat.getFont());
		System.out.println(snapchat.isMusic());
		System.out.println(snapchat.isLocation());
		System.out.println(snapchat.getFilters());
		System.out.println(snapchat.getPrivacy());
		System.out.println(snapchat.getSnapId());
		System.out.println("++++++++++++++++++++++++++++++++++++++++++");
		System.out.println("Invoking Github in main");
		Github github = new Github();
		github.setAccess("public");
		github.setIssue(true);
		github.setLanguage("English");
		github.setLink("Eclipse");
		github.setNoOfBranches(10);
		github.setNoOfPackages(2);
		github.setNoOfProjects(2);
		github.setNoOfRepo(3);
		github.setNotification(true);
		github.setProfilePic(false);
		github.setRepositoryName("Xworkz");
		github.setProjectName("Sign language");
		github.setTheme("White");
		github.setUserName("Harshith");
		System.out.println(github.isIssue());
		System.out.println(github.getAccess());
		System.out.println(github.getLanguage());
		System.out.println(github.getLink());
		System.out.println(github.getNoOfBranches());
		System.out.println(github.getNoOfPackages());
		System.out.println(github.getNoOfProjects());
		System.out.println(github.getNoOfRepo());
		System.out.println(github.getProjectName());
		System.out.println(github.getRepositoryName());
		System.out.println(github.getTheme());
		System.out.println(github.getUserName());
		System.out.println(github.isNotification());
		System.out.println(github.isProfilePic());
		System.out.println("++++++++++++++++++++++++++++++++++++++++++");
		System.out.println("Invoking PhonePe in main");
		PhonePay phonePay = new PhonePay();
		phonePay.setLanguage("English");
		phonePay.setTheme("Light");
		phonePay.setBalance(20000);
		phonePay.setAuthentication(true);
		phonePay.setPhonepeNumber(9611965471l);
		phonePay.setNoOfRewards(15);
		phonePay.setUpiNumber(20134);
		phonePay.setPaymentSuccess(false);
		phonePay.setUpiId("gutti@ybl");
		phonePay.setPassword(3456);
		phonePay.setOtp(1234);
		phonePay.setPaymentMethod("QR");
		phonePay.setBankName("SBI");
		phonePay.setAccNo(675423);
		System.out.println(phonePay.getLanguage());
		System.out.println(phonePay.getTheme());
		System.out.println(phonePay.getBalance());
		System.out.println(phonePay.isAuthentication());
		System.out.println(phonePay.getPhonepeNumber());
		System.out.println(phonePay.getNoOfRewards());
		System.out.println(phonePay.getUpiNumber());
		System.out.println(phonePay.isPaymentSuccess());
		System.out.println(phonePay.getUpiId());
		System.out.println(phonePay.getPassword());
		System.out.println(phonePay.getOtp());
		System.out.println(phonePay.getPaymentMethod());
		System.out.println(phonePay.getBankName());
		System.out.println(phonePay.getAccNo());
		System.out.println("++++++++++++++++++++++++++++++++++++++++++");
		System.out.println("Invoking YouTube in main");
		youTube youtube = new YouTube();
		youtube.setTheme("Dark Mode");
		youtube.setNoOfLikes(1000);
		youtube.setComments(500);
		youtube.setName("Harshith");
		youtube.setYoutubeId("harshith1969927");
		youtube.setFriends(25);
		youtube.setSubcription(true);
		youtube.setLanguage("English");
		youtube.setShare(20);
		youtube.setPrivacy(false);
		youtube.setNoOfAccount(1);
		youtube.setFounder("steve chen");
		youtube.setMembership(true);
		youtube.setHistory(true);
		System.out.println(youtube.getTheme());
		System.out.println(youtube.getNoOfLikes());
		System.out.println(youtube.getComments());
		System.out.println(youtube.getName());
		System.out.println(youtube.getYoutubeId());
		System.out.println(youtube.getFriends());
		System.out.println(youtube.isSubcription());
		System.out.println(youtube.getLanguage());
		System.out.println(youtube.getShare());
		System.out.println(youtube.isPrivacy());
		System.out.println(youtube.getNoOfAccount());
		System.out.println(youtube.getFounder());
		System.out.println(youtube.isMembership());
		System.out.println(youtube.isHistory());
		System.out.println("++++++++++++++++++++++++++++++++++++++++++");
		System.out.println("Invoking Amazon in main");
		Amazon amazon = new Amazon();
		amazon.setAmount(5000);
		amazon.setCart(true);
		amazon.setLoginId("Harshith P Gutti");
		amazon.setNoOfUsers(10000);
		amazon.setNotification(true);
		amazon.setOffer(false);
		amazon.setOrder(true);
		amazon.setPaytype("Online");
		amazon.setPrimeSubscription(true);
		amazon.setQos("Good");
		amazon.setQualtityOfProduct("Good");
		amazon.setShoping(true);
		amazon.setTheme("General");
		amazon.setUserName("Harshith P Gutti");
		System.out.println(amazon.getAmount());
		System.out.println(amazon.getLoginId());
		System.out.println(amazon.getNoOfUsers());
		System.out.println(amazon.getPaytype());
		System.out.println(amazon.getQos());
		System.out.println(amazon.getQualtityOfProduct());
		System.out.println(amazon.getTheme());
		System.out.println(amazon.getUserName());
		System.out.println(amazon.isCart());
		System.out.println(amazon.isNotification());
		System.out.println(amazon.isOffer());
		System.out.println(amazon.isOrder());
		System.out.println(amazon.isPrimeSubscription());
		System.out.println(amazon.isShoping());
		System.out.println("++++++++++++++++++++++++++++++++++++++++++");
		System.out.println("Invoking FaceBook in main");
		FaceBook facebook = new FaceBook();
		facebook.setFaceBookID("Harshith P Gutti");
		facebook.setEmail("harshithpgutti@gmail.com");
		facebook.setNumber(8088019824);
		facebook.setPasswrod("Harshu@2001");
		facebook.setLanguage("Kannada");
		facebook.setTheme("Dark");
		facebook.setSince(2015);
		facebook.setNoOfFriends(35);
		facebook.setNoOfPosts(20);
		facebook.setFounder("Mark Zuckerberg");
		facebook.setNoOfLikes(150);
		facebook.setAccountType("Private");
		facebook.setNoOfComments(50);
		facebook.setProfilePic(true);
		System.out.println(facebook.getFaceBookID());
		System.out.println(facebook.getEmail());
		System.out.println(facebook.getNumber());
		System.out.println(facebook.getPasswrod());
		System.out.println(facebook.getLanguage());
		System.out.println(facebook.getTheme());
		System.out.println(facebook.getSince());
		System.out.println(facebook.getNoOfFriends());
		System.out.println(facebook.getNoOfPosts());
		System.out.println(facebook.getFounder());
		System.out.println(facebook.getNoOfLikes());
		System.out.println(facebook.getAccountType());
		System.out.println(facebook.getNoOfComments());
		System.out.println(facebook.isProfilePic());
		System.out.println("++++++++++++++++++++++++++++++++++++++++++");
		System.out.println("Invoking Netflix in main");
		Netflix netflix = new Netflix();
		netflix.setSubcription(true);
		netflix.setTheme("Light");
		netflix.setAccountName("Harshith");
		netflix.setLanguage("English");
		netflix.setAccountPrivacy("Private");
		netflix.setStreamQuality("HD");
		netflix.setNoOfusers(1000);
		netflix.setLoginId("harshu@2001");
		netflix.setContent("Movies");
		netflix.setOfflineViewing(false);
		netflix.setDownload(true);
		netflix.setAmount(299);
		netflix.setPassword("160701");
		netflix.setFounder(" Scootts Valley");
		System.out.println(netflix.isSubcription());
		System.out.println(netflix.getTheme());
		System.out.println(netflix.getAccountName());
		System.out.println(netflix.getLanguage());
		System.out.println(netflix.getAccountPrivacy());
		System.out.println(netflix.getStreamQuality());
		System.out.println(netflix.getNoOfusers());
		System.out.println(netflix.getLoginId());
		System.out.println(netflix.getContent());
		System.out.println(netflix.isOfflineViewing());
		System.out.println(netflix.isDownload());
		System.out.println(netflix.getAmount());
		System.out.println(netflix.getPassword());
		System.out.println(netflix.getFounder());
		System.out.println("++++++++++++++++++++++++++++++++++++++++++");
		System.out.println("Invoking Irctc in main");
		Irctc irctc = new Irctc();
		irctc.setBooking(true);
		irctc.setDate(12);
		irctc.setFrom("Banglore");
		irctc.setNotification(true);
		irctc.setNumberOfSeats(3);
		irctc.setPricePerTicket(150);
		irctc.setReservationType("General");
		irctc.setSeatAvailable(true);
		irctc.setSeatConfirmation(true);
		irctc.setSeatNumber(98);
		irctc.setTime(12);
		irctc.setTo("Shimoga");
		irctc.setTrainName("Siddaganga");
		irctc.setTrainNumber(12725);
		System.out.println(irctc.getDate());
		System.out.println(irctc.getFrom());
		System.out.println(irctc.getNumberOfSeats());
		System.out.println(irctc.getPricePerTicket());
		System.out.println(irctc.getReservationType());
		System.out.println(irctc.getSeatNumber());
		System.out.println(irctc.getTime());
		System.out.println(irctc.getTo());
		System.out.println(irctc.getTrainName());
		System.out.println(irctc.getTrainNumber());
		System.out.println(irctc.isBooking());
		System.out.println(irctc.isNotification());
		System.out.println(irctc.isSeatAvailable());
		System.out.println(irctc.isSeatConfirmation());
		System.out.println("++++++++++++++++++++++++++++++++++++++++++");
		System.out.println("Invoking LinkedIn in main");
		LinkedIn linkedIn = new LinkedIn();
		linkedIn.setAccess("Public");
		linkedIn.setChat("Text");
		linkedIn.setConnections(350);
		linkedIn.setCreatorMode("Off");
		linkedIn.setEducation("BE");
		linkedIn.setExperience(false);
		linkedIn.setLikes(100);
		linkedIn.setName("Harshith P Gutti");
		linkedIn.setNetwork("Open access");
		linkedIn.setNotification(true);
		linkedIn.setPosts(2);
		linkedIn.setProfilePic(true);
		linkedIn.setSupports(30);
		linkedIn.setSince(2021);
		System.out.println(linkedIn.getAccess());
		System.out.println(linkedIn.getChat());
		System.out.println(linkedIn.getConnections());
		System.out.println(linkedIn.getCreatorMode());
		System.out.println(linkedIn.getEducation());
		System.out.println(linkedIn.getLikes());
		System.out.println(linkedIn.getName());
		System.out.println(linkedIn.getNetwork());
		System.out.println(linkedIn.getPosts());
		System.out.println(linkedIn.getSince());
		System.out.println(linkedIn.getSupports());
		System.out.println(linkedIn.isExperience());
		System.out.println(linkedIn.isNotification());
		System.out.println(linkedIn.isProfilePic());
		System.out.println("++++++++++++++++++++++++++++++++++++++++++");
		System.out.println("Invoking Cred in main");
		Cred cred = new Cred();
		cred.setBankName("SBI");
		cred.setCardType("Credit");
		cred.setCompanyName("fintech");
		cred.setEmail("harshithpgutti@gmail.com");
		cred.setFounder("Kunal Shah");
		cred.setHeadquarter("Banglore");
		cred.setLanguage("English");
		cred.setPhoneNumber(8088019824);
		cred.setPinNumber(200127);
		cred.setRating(5);
		cred.setSafe(true);
		cred.setSince(2018);
		cred.setType("free");
		cred.setUserName("Harshith");
		System.out.println(cred.getBankName());
		System.out.println(cred.getCardType());
		System.out.println(cred.getCompanyName());
		System.out.println(cred.getEmail());
		System.out.println(cred.getFounder());
		System.out.println(cred.getHeadquarter());
		System.out.println(cred.getLanguage());
		System.out.println(cred.getPhoneNumber());
		System.out.println(cred.getPinNumber());
		System.out.println(cred.getRating());
		System.out.println(cred.getSince());
		System.out.println(cred.getType());
		System.out.println(cred.getUserName());
		System.out.println(cred.isSafe());
		System.out.println("++++++++++++++++++++++++++++++++++++++++++");
		System.out.println("Invoking Pubg in main");
		Pubg pubg = new Pubg();
		pubg.setGameName("Pubg MobileLite");
		pubg.setVoice(true);
		pubg.setNoOfPlayers(4);
		pubg.setSince(2000);
		pubg.setVehicle("Bike");
		pubg.setWeapon("Gun");
		pubg.setTeamMembers(30);
		pubg.setChickenDinner(true);
		pubg.setEnemyCount(4);
		pubg.setWeather("Rain");
		pubg.setFootStep(true);
		pubg.setVehicleSpeed(60);
		pubg.setFounder("Greene");
		pubg.setRating(3);
		System.out.println(pubg.getGameName());
		System.out.println(pubg.isVoice());
		System.out.println(pubg.getNoOfPlayers());
		System.out.println(pubg.getSince());
		System.out.println(pubg.getVehicle());
		System.out.println(pubg.getWeapon());
		System.out.println(pubg.getTeamMembers());
		System.out.println(pubg.isChickenDinner());
		System.out.println(pubg.getEnemyCount());
		System.out.println(pubg.getWeather());
		System.out.println(pubg.isFootStep());
		System.out.println(pubg.getVehicleSpeed());
		System.out.println(pubg.getFounder());
		System.out.println(pubg.getRating());
		System.out.println("++++++++++++++++++++++++++++++++++++++++++");
		System.out.println("Invoking Redbus in main");
		Redbus redbus = new Redbus();
		redbus.setPayment("Online Payment");
		redbus.setSms(true);
		redbus.setLanguage("English");
		redbus.setNoOfUsers(100000);
		redbus.setBookingType("Online");
		redbus.setAmount(560);
		redbus.setNoOfTicket(1);
		redbus.setSeatSelection(true);
		redbus.setBusTypes("Sleeper");
		redbus.setDiscount(false);
		redbus.setAccountName("Harshith");
		redbus.setReviews("Good");
		redbus.setGroupBooking(false);
		redbus.setBookingId("harshu@1969");
		System.out.println(redbus.getPayment());
		System.out.println(redbus.isSms());
		System.out.println(redbus.getLanguage());
		System.out.println(redbus.getNoOfUsers());
		System.out.println(redbus.getBookingType());
		System.out.println(redbus.getAmount());
		System.out.println(redbus.getNoOfTicket());
		System.out.println(redbus.isSeatSelection());
		System.out.println(redbus.getBusTypes());
		System.out.println(redbus.isDiscount());
		System.out.println(redbus.getAccountName());
		System.out.println(redbus.getReviews());
		System.out.println(redbus.isGroupBooking());
		System.out.println(redbus.getBookingId());
		System.out.println("++++++++++++++++++++++++++++++++++++++++++");
		System.out.println("Invoking Ola in main");
		Ola ola = new Ola();
		ola.setEmail("harshithpgutti@gmail.com");
		ola.setUserName("Harshith P Gutti");
		ola.setMobileNumber(8088019824);
		ola.setCurrentLocation("Nagsandra");
		ola.setDestinationLocation("Majestic");
		ola.setProfilePic(true);
		ola.setVehicle("Car");
		ola.setNoOfPeople(4);
		ola.setOtp(4590);
		ola.setPaymentMethod("Cash");
		ola.setVehicleNumber("KA14J9484");
		ola.setNoOfRides(20);
		ola.setCost(50);
		ola.setCancellationRate(20);
		System.out.println(ola.getEmail());
		System.out.println(ola.getUserName());
		System.out.println(ola.getMobileNumber());
		System.out.println(ola.getCurrentLocation());
		System.out.println(ola.getDestinationLocation());
		System.out.println(ola.isProfilePic());
		System.out.println(ola.getVehicle());
		System.out.println(ola.getNoOfPeople());
		System.out.println(ola.getOtp());
		System.out.println(ola.getPaymentMethod());
		System.out.println(ola.getVehicleNumber());
		System.out.println(ola.getNoOfRides());
		System.out.println(ola.getCost());
		System.out.println(ola.getCancellationRate());
		System.out.println("++++++++++++++++++++++++++++++++++++++++++");
		System.out.println("Invoking Uber in main");
		Uber uber = new Uber();
		uber.setConfirmation(true);
		uber.setCost(250);
		uber.setCurrentLocation("Nagsandra");
		uber.setDestination("Majestic");
		uber.setEmail("harshithpgutti@gmail.com");
		uber.setMobileNumber(8088019824);
		uber.setNoOfPeople(3);
		uber.setNoOfRides(2);
		uber.setOtp(566466);
		uber.setPaymentMode("Online");
		uber.setRating(5);
		uber.setUserName("Harshith P gutti");
		uber.setVehicle("Auto");
		uber.setVehicleNumber("KA02MN7029");
		System.out.println(uber.getCost());
		System.out.println(uber.getCurrentLocation());
		System.out.println(uber.getDestination());
		System.out.println(uber.getEmail());
		System.out.println(uber.getMobileNumber());
		System.out.println(uber.getNoOfPeople());
		System.out.println(uber.getNoOfRides());
		System.out.println(uber.getOtp());
		System.out.println(uber.getPaymentMode());
		System.out.println(uber.getRating());
		System.out.println(uber.getUserName());
		System.out.println(uber.getVehicle());
		System.out.println(uber.getVehicleNumber());
		System.out.println(uber.isConfirmation());
		System.out.println("++++++++++++++++++++++++++++++++++++++++++");
		System.out.println("Invoking Rapido in main");
		Rapido rapido = new Rapido();
		rapido.setConfiramtion(true);
		rapido.setCost(250);
		rapido.setCurrentLocation("Rajajinagar");
		rapido.setDropLocation("Malleshwaram");
		rapido.setLanguage("Kannada");
		rapido.setNumber(8088019824);
		rapido.setOnTime(true);
		rapido.setOtp(349908);
		rapido.setPayMode("Cash");
		rapido.setRating(4);
		rapido.setRides(3);
		rapido.setTime(6);
		rapido.setUserName("Harshith");
		rapido.setVehicle("Bike");
		System.out.println(rapido.getCost());
		System.out.println(rapido.getCurrentLocation());
		System.out.println(rapido.getDropLocation());
		System.out.println(rapido.getLanguage());
		System.out.println(rapido.getNumber());
		System.out.println(rapido.getOtp());
		System.out.println(rapido.getPayMode());
		System.out.println(rapido.getRating());
		System.out.println(rapido.getRides());
		System.out.println(rapido.getTime());
		System.out.println(rapido.getUserName());
		System.out.println(rapido.getVehicle());
		System.out.println(rapido.isConfiramtion());
		System.out.println(rapido.isOnTime());
		System.out.println("++++++++++++++++++++++++++++++++++++++++++");
		System.out.println("Invoking NammaYatri in main");
		NammaYatri nammaYatri = new NammaYatri();
		NammaYatri nammayatri = new NammaYatri();
		nammayatri.setPrice(50);
		nammayatri.setCurrentLocation("Rajajinagar");
		nammayatri.setDestination("8th mile");
		nammayatri.setOtp(1234);
		nammayatri.setNoOfPeople(3);
		nammayatri.setLanguage("Kannada");
		nammayatri.setNoOfRides(2);
		nammayatri.setContactNo(8088019824);
		nammayatri.setCancellationRate(50);
		nammayatri.setPaymentType("Online");
		nammayatri.setNoPlateColor("Yellow");
		nammayatri.setUserName("Harshith");
		nammayatri.setVehicleNo("KA14EG7464");
		nammayatri.setPassword("452156");
		System.out.println(nammayatri.getPrice());
		System.out.println(nammayatri.getCurrentLocation());
		System.out.println(nammayatri.getDestination());
		System.out.println(nammayatri.getOtp());
		System.out.println(nammayatri.getNoOfPeople());
		System.out.println(nammayatri.getLanguage());
		System.out.println(nammayatri.getNoOfRides());
		System.out.println(nammayatri.getContactNo());
		System.out.println(nammayatri.getCancellationRate());
		System.out.println(nammayatri.getPaymentType());
		System.out.println(nammayatri.getNoPlateColor());
		System.out.println(nammayatri.getUserName());
		System.out.println(nammayatri.getVehicleNo());
		System.out.println(nammayatri.getPassword());
		System.out.println("++++++++++++++++++++++++++++++++++++++++++");
		System.out.println("Invoking NammaMetro in main");
		NammaMetro nammaMetro = new NammaMetro();
		nammaMetro.setLanguage("English");
		nammaMetro.setFromStation("Nagsandra");
		nammaMetro.setToStation("Jaynagar");
		nammaMetro.setFare(60);
		nammaMetro.setUserName("Harshtih P Gutti");
		nammaMetro.setEmail("harshithpgutti@gmail.com");
		nammaMetro.setTicket("QR Ticket");
		nammaMetro.setRating(4);
		nammaMetro.setNoOfPassengers(3000);
		nammaMetro.setLine1("Green Line");
		nammaMetro.setLine2("Green Line");
		nammaMetro.setFrequency("15 mins");
		nammaMetro.setSince(2014);
		nammaMetro.setOwner("BMRCL");
		System.out.println(nammaMetro.getLanguage());
		System.out.println(nammaMetro.getFromStation());
		;
		System.out.println(nammaMetro.getToStation());
		System.out.println(nammaMetro.getFare());
		System.out.println(nammaMetro.getUserName());
		System.out.println(nammaMetro.getEmail());
		System.out.println(nammaMetro.getTicket());
		System.out.println(nammaMetro.getRating());
		System.out.println(nammaMetro.getNoOfPassengers());
		System.out.println(nammaMetro.getLine1());
		System.out.println(nammaMetro.getLine2());
		System.out.println(nammaMetro.getFrequency());
		System.out.println(nammaMetro.getSince());
		System.out.println(nammaMetro.getOwner());

	}

}
